### ISSUE TITLE
Fix update all fields in client

### ISSUE THREAD

**Issue by hemiSRT8** [xpinjection/hibernate-basics#1]
Hi Igor and Mikalai,

Thank you for amazing job done while preparing hibernate-basics course

Could you please suggest whether it makes sense to add comment into FlushTest.updateAllFields() so that it is clear update of all fields may be fixed via **org.hibernate.annotations.DynamicUpdate** ?

Unfortunately I cannot create merge request due to the access issues

**Comment by xpinjection** [comment]
We don’t have such comments because repository is just an assistance to the talk and hard to be used separately. If you find such comments useful, please create PR.

**Comment by hemiSRT8** [comment]
Thanks
Please review https://github.com/xpinjection/hibernate-basics/pull/2
